# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Pre-release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: jlinkZip with Gradle
      run: ./gradlew jlinkZip
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        # GitHub secret token
        repo_token: ${{secrets.repo_token}}
        # Git tag (for automatic releases)
        automatic_release_tag: latest # optional
        # Should this release be marked as a pre-release?
        prerelease: true # optional, default is true
        # Assets to upload to the release
        files: |
          build/image.zip
