# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Pre-release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-14
      with:
        args: jlinkCustomZip
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        title : Automatic Latest Pre-release
        # GitHub secret token
        repo_token: ${{secrets.repo_token}}
        # Git tag (for automatic releases)
        automatic_release_tag: latest # optional
        # Should this release be marked as a pre-release?
        prerelease: true # optional, default is true
        # Assets to upload to the release
        files: |
          build/image.zip
